In [0]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from sklearn.ensemble import RandomForestClassifier

%matplotlib inline

In [0]:
!pip install chembl_webresource_client

     |████████████████████████████████| 61kB 4.0MB/s 
     |████████████████████████████████| 61kB 8.1MB/s 
     |████████████████████████████████| 61kB 28.0MB/s 
     |████████████████████████████████| 2.3MB 54.3MB/s 
     |████████████████████████████████| 102kB 38.0MB/s 
  Created wheel for chembl-webresource-client: filename=chembl_webresource_client-0.9.31-cp36-none-any.whl size=57597 sha256=1b853519f33823afbfe3529aa4c355b359d16747e98c1ef2a7cc6f7ec745221d
  Stored in directory: /root/.cache/pip/wheels/ee/03/9f/d048ad0636fc02b4280a80af144bdd95551d41b0900263ba47
  Created wheel for grequests: filename=grequests-0.2.0-cp36-none-any.whl size=3098 sha256=3f50383ec0a8a494d86ab2e7e6e0845ae20023530f9056a9c7a57d586131c4a6
  Stored in directory: /root/.cache/pip/wheels/01/cd/06/f81d8c2eccff117a6c56882ab6c825a5ab964ef70f150137a8
  Created wheel for gevent-openssl: filename=gevent_openssl-1.2-cp36-none-any.whl size=4094 sha256=0529c6130e7a8e0b5a56611dfd9fade0e457de097b7f8af701b1d2047acc8d23
 

In [0]:
import gevent.monkey

In [0]:
gevent.monkey.patch_all()

NameError: ignored

In [0]:
from chembl_webresource_client.new_client import new_client

/usr/local/lib/python3.6/dist-packages/grequests.py:21: MonkeyPatchWarning: Monkey-patching ssl after ssl has already been imported may lead to errors, including RecursionError on Python 3.6. It may also silently lead to incorrect behaviour on Python 3.7. Please monkey-patch earlier. See https://github.com/gevent/gevent/issues/1016. Modules that had direct imports (NOT patched): ['urllib3.util (/usr/local/lib/python3.6/dist-packages/urllib3/util/__init__.py)', 'urllib3.contrib.pyopenssl (/usr/local/lib/python3.6/dist-packages/urllib3/contrib/pyopenssl.py)']. 
  curious_george.patch_all(thread=False, select=False)


In [0]:
import sys
import os
import requests
import subprocess
import shutil
from logging import getLogger, StreamHandler, INFO


logger = getLogger(__name__)
logger.addHandler(StreamHandler())
logger.setLevel(INFO)


def install(
        chunk_size=4096,
        file_name="Miniconda3-latest-Linux-x86_64.sh",
        url_base="https://repo.continuum.io/miniconda/",
        conda_path=os.path.expanduser(os.path.join("~", "miniconda")),
        rdkit_version=None,
        add_python_path=True,
        force=False):
    """install rdkit from miniconda
    ```
    import rdkit_installer
    rdkit_installer.install()
    ```
    """

    python_path = os.path.join(
        conda_path,
        "lib",
        "python{0}.{1}".format(*sys.version_info),
        "site-packages",
    )

    if add_python_path and python_path not in sys.path:
        logger.info("add {} to PYTHONPATH".format(python_path))
        sys.path.append(python_path)

    if os.path.isdir(os.path.join(python_path, "rdkit")):
        logger.info("rdkit is already installed")
        if not force:
            return

        logger.info("force re-install")

    url = url_base + file_name
    python_version = "{0}.{1}.{2}".format(*sys.version_info)

    logger.info("python version: {}".format(python_version))

    if os.path.isdir(conda_path):
        logger.warning("remove current miniconda")
        shutil.rmtree(conda_path)
    elif os.path.isfile(conda_path):
        logger.warning("remove {}".format(conda_path))
        os.remove(conda_path)

    logger.info('fetching installer from {}'.format(url))
    res = requests.get(url, stream=True)
    res.raise_for_status()
    with open(file_name, 'wb') as f:
        for chunk in res.iter_content(chunk_size):
            f.write(chunk)
    logger.info('done')

    logger.info('installing miniconda to {}'.format(conda_path))
    subprocess.check_call(["bash", file_name, "-b", "-p", conda_path])
    logger.info('done')

    logger.info("installing rdkit")
    subprocess.check_call([
        os.path.join(conda_path, "bin", "conda"),
        "install",
        "--yes",
        "-c", "rdkit",
        "python=={}".format(python_version),
        "rdkit" if rdkit_version is None else "rdkit=={}".format(rdkit_version)])
    logger.info("done")

    import rdkit
    logger.info("rdkit-{} installation finished!".format(rdkit.__version__))


if __name__ == "__main__":
    install()

add /root/miniconda/lib/python3.6/site-packages to PYTHONPATH
python version: 3.6.8
fetching installer from https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
done
installing miniconda to /root/miniconda
done
installing rdkit
done
rdkit-2019.03.4 installation finished!


In [0]:
from rdkit import Chem
generatedMol = ["PCPPOO","PPPCPCPO", "Cl.CNCN1C2CCCC2CCC2CCCCC12", "CCCPCPCO", "CNPCP=O", "CC1=C(CC(=O)O)c2cc(Cl)ccc2/C/1=C\c1ccc(cc1)F", "NC(=O)c1ccc(I)c(c1)F", "PPNCCCCPO", "CN1CCCC1c2cccnc2", "CC(C)[C@H](N)C(=O)N1CCC[C@H]1S(O)O"]
inputMols = []
for smiles in generatedMol:
  inputMols.append(Chem.MolFromSmiles(smiles))
generatedMol = inputMols



In [0]:
generatedMol

Changes in molecules: 3, 7(deleted)

In [0]:
!pip install boost-py

In [0]:
n = 10
from rdkit.Chem import Descriptors
properties = ["Mol_weight","FpDensityMorgan1","MaxAbsPartialCharge","NumHeavyAtoms","NumRotatableBonds","NumAromaticRings", "NumHBA", "NumHBD", "NumLipinskiHBA", "NumLipinskiHBD", "TPSA", "QED_CALC", "LOGP"]
propArr = {}
for factor in properties:
  propArr[factor] = []
value = 0 
for i in range(0,n):
  for factor in properties:
    if factor == "Mol_weight":
      value = Descriptors.ExactMolWt(generatedMol[i])
      propArr[factor].append(value)
    if factor == "FpDensityMorgan1":
      value = Descriptors.FpDensityMorgan1(generatedMol[i])
      propArr[factor].append(value)
    if factor == "MaxAbsPartialCharge":
      value = Descriptors.MaxAbsPartialCharge(generatedMol[i])
      propArr[factor].append(value)
    if factor == "NumHeavyAtoms":
      value = Chem.Lipinski.HeavyAtomCount(generatedMol[i])
      propArr[factor].append(value)
    if factor == "NumRotatableBonds":
      value = Chem.rdMolDescriptors.CalcNumRotatableBonds(generatedMol[i])
      propArr[factor].append(value)
    if factor == "NumAromaticRings":
      value = Chem.rdMolDescriptors.CalcNumAromaticRings(generatedMol[i])
      propArr[factor].append(value)
    if factor == "NumHBA":
      value = Chem.rdMolDescriptors.CalcNumHBA(generatedMol[i])
      propArr[factor].append(value)
    if factor == "NumHBD":
      value = Chem.rdMolDescriptors.CalcNumHBD(generatedMol[i])
      propArr[factor].append(value) 
    if factor == "NumLipinskiHBA":
      value = Chem.rdMolDescriptors.CalcNumLipinskiHBA(generatedMol[i])
      propArr[factor].append(value)
    if factor == "NumLipinskiHBD":
      value = Chem.rdMolDescriptors.CalcNumLipinskiHBD(generatedMol[i])
      propArr[factor].append(value)
    if factor == "TPSA":
      value = Chem.rdMolDescriptors.CalcTPSA(generatedMol[i])
      propArr[factor].append(value) 
    if factor == "QED_CALC":
      value = Chem.QED.weights_mean(generatedMol[i])
      propArr[factor].append(value) 
    if factor == "LOGP":
      value = Chem.Crippen.MolLogP(generatedMol[i])
      propArr[factor].append(value) 
      
  

In [0]:
for factor in properties:
  print(propArr[factor])

[143.96588935399998, 205.949798122, 272.201926608, 152.051988328, 123.000287104, 328.066635588, 264.93999, 185.028823958, 162.115698448, 214.14887286799998]
[1.8333333333333333, 1.375, 0.8333333333333334, 1.375, 2.0, 1.173913043478261, 1.5454545454545454, 1.4444444444444444, 1.5833333333333333, 1.5333333333333334]
[0.24841083892000726, 0.3766913711794849, 0.30737005286996916, 0.3921451992976817, 0.3006031250116542, 0.4809857797948595, 0.3655979974287135, 0.37704060873041706, 0.29930714879016557, 0.47522904009758193]
[6, 8, 18, 8, 6, 23, 11, 9, 12, 15]
[3, 5, 2, 5, 3, 3, 1, 6, 1, 3]
[0, 0, 0, 0, 0, 2, 1, 0, 1, 0]
[2, 1, 2, 1, 2, 1, 1, 2, 2, 4]
[1, 1, 1, 1, 1, 1, 1, 2, 0, 3]
[2, 1, 2, 1, 2, 2, 2, 2, 2, 5]
[1, 1, 1, 1, 1, 1, 2, 2, 0, 4]
[29.46, 20.23, 15.27, 20.23, 29.1, 37.3, 43.09, 32.26, 16.130000000000003, 86.79]
[0.2811560560882514, 0.5396149395799648, 0.8288178053092322, 0.46884388945711564, 0.4484639590058735, 0.831714405034419, 0.7685993998815334, 0.4828383650020144, 0.62615182257

In [0]:
import pandas as pd
index1 = []
for i in range(1,11):
    index1.append(i)

data = pd.DataFrame(data = propArr, index = index1)

In [0]:
#LinpinskiRuleCheck
check = [0]*10

for i in range(0,10):
  if propArr["Mol_weight"][i] > 500:
    check[i] += 1
  if propArr["NumLipinskiHBA"][i] > 10:
    check[i] += 1
  if propArr["NumLipinskiHBD"][i] > 5:
    check[i] += 1
  if propArr["LOGP"][i] > 5:
    check[i] += 1
    

In [0]:
#GeneralRo5Check

check0 = [0]*10

for i in range(0,10):
  if propArr["Mol_weight"][i] > 500:
    check[i] += 1
  if propArr["NumHBA"][i] > 10:
    check[i] += 1
  if propArr["NumHBD"][i] > 5:
    check[i] += 1
  if propArr["LOGP"][i] > 5:
    check[i] += 1

In [0]:
#ro3 check

check1 = [1]*10

for i in range(0,10):
  if propArr["Mol_weight"][i] > 300:
    check1[i] = 0
    break
  if propArr["NumHBA"][i] > 3:
    check1[i] = 0
    break
  if propArr["NumHBD"][i] > 3:
    check1[i] = 0
    break
  if propArr["LOGP"][i] > 3:
    check1[i] = 0
    break
    
 

In [0]:
#adding ro5 and ro3 results

addProps = ["num_lipinski_ro5_violations","num_ro5_violations", "ro3_pass"]

for prop in addProps:
  propArr[prop] = []
value = 0
for i in range(0,n):
  
    value = check[i]
    propArr["num_lipinski_ro5_violations"].append(value)
    value = check0[i]
    propArr["num_ro5_violations"].append(value)
    value = check1[i]
    propArr["ro3_pass"].append(value)
    
    
    
   
    

                       


In [0]:
propArr

{'FpDensityMorgan1': [1.8333333333333333,
  1.375,
  1.625,
  1.375,
  2.0,
  1.375,
  1.5,
  1.4444444444444444,
  1.5714285714285714,
  1.5555555555555556],
 'LOGP': [1.4955999999999996,
  2.2278000000000002,
  1.6738000000000008,
  1.6606999999999996,
  1.0484999999999998,
  1.5164999999999995,
  1.6899000000000002,
  1.3255999999999997,
  1.689,
  0.8820999999999999],
 'MaxAbsPartialCharge': [0.24841083892000726,
  0.3766913711794849,
  0.3723929636568515,
  0.3921451992976817,
  0.3006031250116542,
  0.39215775458243435,
  0.37145438006972026,
  0.37704060873041706,
  0.37243909087773575,
  0.39223983835538156],
 'Mol_weight': [143.96588935399998,
  205.949798122,
  171.013173894,
  152.051988328,
  123.000287104,
  170.01792492599998,
  206.94504708999997,
  185.028823958,
  173.958695798,
  129.1153641],
 'NumAromaticRings': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 'NumHBA': [2, 1, 2, 1, 2, 1, 2, 2, 2, 2],
 'NumHBD': [1, 1, 2, 1, 1, 1, 2, 2, 2, 2],
 'NumHeavyAtoms': [6, 8, 8, 8, 6, 8, 8

In [0]:
!pip install chembl_webresource_client

In [0]:

drug_indication = new_client.drug_indication
molecules = new_client.molecule
lung_cancer_ind = drug_indication.filter(efo_term__icontains="LUNG CARCINOMA")
lung_cancer_mols = molecules.filter(molecule_chembl_id__in=[x['molecule_chembl_id'] for x in lung_cancer_ind])

In [0]:
lung_cancer_mols

[{'atc_classifications': ['N07BA01'], 'availability_type': '2', 'biotherapeutic': None, 'black_box_warning': '0', 'chebi_par_id': 17688, 'chirality': '1', 'cross_references': [{'xref_id': 'nicotine', 'xref_name': 'nicotine', 'xref_src': 'DailyMed'}, {'xref_id': 'nicotine%20polacrilex', 'xref_name': 'nicotine polacrilex', 'xref_src': 'DailyMed'}, {'xref_id': '144209012', 'xref_name': 'SID: 144209012', 'xref_src': 'PubChem'}, {'xref_id': '144210494', 'xref_name': 'SID: 144210494', 'xref_src': 'PubChem'}, {'xref_id': '17389805', 'xref_name': 'SID: 17389805', 'xref_src': 'PubChem'}, {'xref_id': '26752744', 'xref_name': 'SID: 26752744', 'xref_src': 'PubChem'}, {'xref_id': '26752745', 'xref_name': 'SID: 26752745', 'xref_src': 'PubChem'}, {'xref_id': '26752746', 'xref_name': 'SID: 26752746', 'xref_src': 'PubChem'}, {'xref_id': '50105392', 'xref_name': 'SID: 50105392', 'xref_src': 'PubChem'}, {'xref_id': '50105393', 'xref_name': 'SID: 50105393', 'xref_src': 'PubChem'}, {'xref_id': '56314824', 

In [0]:
import pandas as pd



    
arr = lung_cancer_mols[0]['molecule_properties']

arr['active'] = 1
arr_labels = []
for key in arr.keys():
    arr_labels.append(key)
a = []
for i in range(23):
    a.append([])   
    


for q in range(0,23):
    a[q].append(arr[arr_labels[q]])
    
    


index = []
for p in range(1,50):
    count = 1
    list1 = lung_cancer_mols[p]['molecule_properties']
    
    if list1 != None:
      list1['active'] = 1
      if lung_cancer_mols[p]['molecule_properties'] != None and lung_cancer_mols[p]['molecule_properties']['alogp'] != None and lung_cancer_mols[p]['molecule_properties']['full_mwt'] != None:
        if float(lung_cancer_mols[p]['molecule_properties']['full_mwt']) <= float(300):

          for j in range(0,23):
              a[j].append(list1[arr_labels[j]])
          count += 1

l1 = len(a[0])
def makeDict(list1, list2):
    new_Dict = {}
    for i in range(0,23):
        new_Dict[list1[i]] = list2[i]
    return new_Dict
for i in range(1,l1+1):
    index.append(i)

data2 = pd.DataFrame(data = makeDict(arr_labels, a),index = index, copy = True)
data2 = data2[arr_labels]
data2.head()

acd_logd acd_logp acd_most_apka  ... ro3_pass rtb  active
1    -0.62     0.57          None  ...        Y   1       1
2    -1.68      1.4          3.48  ...        N   2       1
3     1.04     1.04          None  ...        N   4       1
4     -1.8     -1.8         10.56  ...        N   0       1
5     0.33     0.33          10.7  ...        N   1       1

[5 rows x 23 columns]

In [0]:
orig = len(data2)



y = []
for i in range (0,l1):
  y.append([])
predProps = {'acd_logd','acd_logp', 'mw_monoisotopic', 'mw_freebase'}
data2['acd_logd'] = data2['acd_logd'].apply(pd.to_numeric, errors = 'ignore')
data2['acd_logp'] = data2['acd_logp'].apply(pd.to_numeric, errors = 'ignore')
data2['mw_monoisotopic'] = data2['mw_monoisotopic'].apply(pd.to_numeric, errors = 'ignore')
data2['mw_freebase'] = data2['mw_freebase'].apply(pd.to_numeric, errors = 'ignore')
y[0] = data2['active'].values
y[1] = data2['acd_logd'].values
y[2] = data2['acd_logp'].values
y[3] = data2['mw_freebase'].values
y[4] = data2['mw_monoisotopic'].values


    
data2.drop(labels = ['active', 'acd_logd','acd_logp','mw_monoisotopic','mw_freebase','molecular_species', 'acd_most_apka', 'acd_most_bpka', 'full_molformula'], axis = 1, inplace = True)
data2['ro3_pass'].replace(to_replace=['Y'], value = 1,inplace=True)
data2['ro3_pass'].replace(to_replace = ['N'], value = 0, inplace=True)
data2 = data2.apply(pd.to_numeric, errors = 'ignore')
X = data2.iloc[::].values


In [0]:
y[1][4]

-1.68

In [0]:
X

array([[ 1.8500e+00,  1.0000e+00,  1.6224e+02,  2.0000e+00,  2.0000e+00,
         0.0000e+00,  0.0000e+00,  1.2000e+01,  0.0000e+00,  0.0000e+00,
         1.6130e+01,  6.3000e-01,  1.0000e+00,  1.0000e+00],
       [ 6.8600e+00,  1.0000e+00,  3.9156e+02,  2.0000e+00,  3.0000e+00,
         2.0000e+00,  2.0000e+00,  2.9000e+01,  1.0000e+00,  1.0000e+00,
         4.9330e+01,  3.2000e-01,  0.0000e+00,  6.0000e+00],
       [ 6.1800e+00,  0.0000e+00,  9.1419e+02,  1.3000e+01,  1.4000e+01,
         3.0000e+00,  3.0000e+00,  6.5000e+01,  3.0000e+00,  3.0000e+00,
         1.9543e+02,  1.6000e-01,  0.0000e+00,  6.0000e+00],
       [ 0.0000e+00,  2.0000e+00,  5.4353e+02,  1.2000e+01,  1.2000e+01,
         6.0000e+00,  7.0000e+00,  3.9000e+01,  3.0000e+00,  3.0000e+00,
         2.0607e+02,  2.4000e-01,  0.0000e+00,  5.0000e+00],
       [ 1.3100e+00,  1.0000e+00,  1.8016e+02,  3.0000e+00,  4.0000e+00,
         1.0000e+00,  1.0000e+00,  1.3000e+01,  0.0000e+00,  0.0000e+00,
         6.3600e+01,  5.50

In [0]:
from statistics import median
import numpy as np
import math
for i in range(0,orig):
    for j in range(0, len(X[i])):
        lst = []
        if math.isnan(X[i][j]):
            for b in range(0,orig):
                if math.isnan(X[b][j]) == False:
                    
                    lst.append(X[b][j])
            X[i][j] = median(lst)
            
for i in range(0,orig):
    for j in range(0, len(X[i])):
        X[i][j] = np.float32(X[i][j])
def median(lst):
    sortedLst = sorted(lst)
    lstLen = len(lst)
    index = (lstLen - 1) // 2

    if (lstLen % 2):
        return sortedLst[index]
    else:
        return (sortedLst[index] + sortedLst[index + 1])/2.0
 

In [0]:
data3 = {}



for i in range(0,n):
  if i == 0:
    data3['alogp'] = []
    data3['aromatic_rings'] = []
    data3['full_mwt'] = []
    data3['hba'] = []
    data3['hba_lipinski'] = []
    data3['hbd'] = []
    data3['hbd_lipinski'] = []
    data3['heavy_atoms'] = []
    data3['num_lipinski_ro5_violations'] = []
    data3['num_ro5_violations'] = []
    data3['psa'] = []
    data3['qed_weighted'] = [] 
    data3['ro3_pass'] = []
    data3['rtb'] = []
    
  data3['alogp'].append(propArr["LOGP"][i])
  data3['aromatic_rings'].append(propArr["NumAromaticRings"][i])
  data3['full_mwt'].append(propArr["Mol_weight"][i])
  data3['hba'].append(propArr["NumHBA"][i])
  data3['hba_lipinski'].append(propArr["NumLipinskiHBA"][i])
  data3['hbd'].append(propArr["NumHBD"][i])
  data3['hbd_lipinski'].append(propArr["NumLipinskiHBD"][i])
  data3['heavy_atoms'].append(propArr["NumHeavyAtoms"][i])
  data3['num_lipinski_ro5_violations'].append(propArr["num_lipinski_ro5_violations"][i])
  data3['num_ro5_violations'].append(propArr["num_ro5_violations"][i])
  data3['psa'].append(propArr["TPSA"][i])
  data3['qed_weighted'].append(propArr["QED_CALC"][i])
  data3['ro3_pass'].append(propArr['ro3_pass'][i])
  data3['rtb'].append(propArr['NumRotatableBonds'][i])
  
index = []
for q in range(1,11):
  index.append(q)
      
X_test1 = pd.DataFrame(data = data3, index = index) 
X_test1 = X_test1.apply(pd.to_numeric, errors = 'ignore')
X_test1.head()

alogp  aromatic_rings    full_mwt  hba  ...    psa  qed_weighted  ro3_pass  rtb
1  1.4956               0  143.965889    2  ...  29.46      0.281156         1    3
2  2.2278               0  205.949798    1  ...  20.23      0.539615         1    5
3  3.4084               0  272.201927    2  ...  15.27      0.828818         0    2
4  1.6607               0  152.051988    1  ...  20.23      0.468844         1    5
5  1.0485               0  123.000287    2  ...  29.10      0.448464         1    3

[5 rows x 14 columns]

In [0]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
#Y will be used to collect the calculated properties for each of the 10 compounds
Y = {}
predProps2 = ['acd_logd','acd_logp', 'mw_monoisotopic', 'mw_freebase']
acc = []
for i in range(0,4):
  #division of main dataset
  X_train, X_test, y_train, y_test = train_test_split(X, y[i+1], test_size = 0.3, random_state = 0)
  rf = RandomForestRegressor(n_estimators = 50)
  
  #Fitting the training datasets
  rf.fit(X_train,y_train)
  #Predicted values
  pred = rf.predict(X_test)
  counter = 0 
  for j in range(0, len(pred)):
    #accuracy
    if pred[j] >= 0.9*y_test[j] and pred[j] <= 1.1*(y_test[j]):
      counter += 1
  print(counter/len(pred)*100)
  #properties for new generated compounds
  Y_test1 = rf.predict(X_test1)
  Y[predProps2[i]] = Y_test1

0.0
0.0
83.33333333333334
83.33333333333334


In [0]:
for predProps in predProps2:
  print(Y[predProps])

[-0.5388  0.1662  1.4006 -0.2488 -0.5396  1.463   0.4802 -0.3572 -0.6168
  1.6568]
[0.1148 1.7608 1.7682 0.8926 0.0422 1.8458 0.594  0.9434 0.485  0.3762]
[141.6104 191.7374 247.2078 146.7844 142.4876 249.2934 208.866  152.2892
 165.6216 220.7294]
[137.199084 172.413834 242.0601   146.270592 135.19452  242.681258
 177.998584 150.987822 161.404806 228.925114]


In [0]:
for i in range(0,n):
  if i == 0:
    data3['mw_freebase'] = []
    data3['mw_monoisotopic'] = []
    
  data3['mw_freebase'].append(Y[predProps2[2]][i])
  data3['mw_monoisotopic'].append(Y[predProps2[3]][i])
  
  
X_test1 = pd.DataFrame(data = data3, index = index)
X_test1 = X_test1.apply(pd.to_numeric, errors = 'ignore')
cols = X_test1.columns.tolist()
temp = cols[14]
cols[14] = cols[15]
cols [15] = temp
print(cols)
cols = cols[0:8] + cols[-2:] + cols [8:(len(cols)-2)]
X_test1 = X_test1[cols]


['alogp', 'aromatic_rings', 'full_mwt', 'hba', 'hba_lipinski', 'hbd', 'hbd_lipinski', 'heavy_atoms', 'num_lipinski_ro5_violations', 'num_ro5_violations', 'psa', 'qed_weighted', 'ro3_pass', 'rtb', 'mw_monoisotopic', 'mw_freebase']


In [0]:
X_test1.head()

alogp  aromatic_rings    full_mwt  hba  ...    psa  qed_weighted  ro3_pass  rtb
1  1.4956               0  143.965889    2  ...  29.46      0.281156         1    3
2  2.2278               0  205.949798    1  ...  20.23      0.539615         1    5
3  3.4084               0  272.201927    2  ...  15.27      0.828818         0    2
4  1.6607               0  152.051988    1  ...  20.23      0.468844         1    5
5  1.0485               0  123.000287    2  ...  29.10      0.448464         1    3

[5 rows x 16 columns]

In [0]:
X_test2 = X_test1.iloc[::].values

In [0]:
import pandas as pd



    
arr = lung_cancer_mols[0]['molecule_properties']

arr['active'] = 1
arr_labels = []
for key in arr.keys():
    arr_labels.append(key)
a = []
for i in range(23):
    a.append([])   
    


for q in range(0,23):
    a[q].append(arr[arr_labels[q]])
    
    


index = []
for p in range(1,50):
    count = 1
    list1 = lung_cancer_mols[p]['molecule_properties']
    
    if list1 != None:
      list1['active'] = 1
      if lung_cancer_mols[p]['molecule_properties'] != None and lung_cancer_mols[p]['molecule_properties']['alogp'] != None and lung_cancer_mols[p]['molecule_properties']['full_mwt'] != None:
        if float(lung_cancer_mols[p]['molecule_properties']['full_mwt']) <= float(350):
          for j in range(0,23):
              a[j].append(list1[arr_labels[j]])
          count += 1

l1 = len(a[0])
def makeDict(list1, list2):
    new_Dict = {}
    for i in range(0,23):
        new_Dict[list1[i]] = list2[i]
    return new_Dict
for i in range(1,l1+1):
    index.append(i)
    
dataLung = pd.DataFrame(data = makeDict(arr_labels, a),index = index, copy = True)
dataLung = dataLung[arr_labels]
dataLung.head()

acd_logd acd_logp acd_most_apka  ... ro3_pass rtb  active
1    -0.62     0.57          None  ...        Y   1       1
2    -1.68      1.4          3.48  ...        N   2       1
3     3.62     6.26          4.73  ...        N   5       1
4     1.04     1.04          None  ...        N   4       1
5     -1.8     -1.8         10.56  ...        N   0       1

[5 rows x 23 columns]

In [0]:

drug_indication = new_client.drug_indication
molecules = new_client.molecule
ovary_cancer_ind = drug_indication.filter(efo_term__icontains="OVARIAN NEOPLASM")
ovary_cancer_mols = molecules.filter(molecule_chembl_id__in=[x['molecule_chembl_id'] for x in ovary_cancer_ind])

In [0]:
drug_indication = new_client.drug_indication
molecules = new_client.molecule
pancreatic_cancer_ind = drug_indication.filter(efo_term__icontains="PANCREATIC NEOPLASM")
pancreatic_cancer_mols = molecules.filter(molecule_chembl_id__in=[x['molecule_chembl_id'] for x in pancreatic_cancer_ind])

In [0]:
#tb
drug_indication = new_client.drug_indication
molecules = new_client.molecule
tb_ind = drug_indication.filter(efo_term__icontains="TUBERCULOSIS")
tb_mols = molecules.filter(molecule_chembl_id__in=[x['molecule_chembl_id'] for x in tb_ind])




In [0]:
pancreatic_cancer_mols[0]['molecule_properties']

{'acd_logd': '2.08',
 'acd_logp': '3.73',
 'acd_most_apka': '11.2',
 'acd_most_bpka': '9.33',
 'alogp': '4.09',
 'aromatic_rings': 3,
 'full_molformula': 'C33H38N4O6',
 'full_mwt': '586.69',
 'hba': 9,
 'hba_lipinski': 10,
 'hbd': 1,
 'hbd_lipinski': 1,
 'heavy_atoms': 43,
 'molecular_species': 'BASE',
 'mw_freebase': '586.69',
 'mw_monoisotopic': '586.2791',
 'num_lipinski_ro5_violations': 1,
 'num_ro5_violations': 1,
 'psa': '114.2',
 'qed_weighted': '0.36',
 'ro3_pass': 'N',
 'rtb': 4}

In [0]:
import pandas as pd



    
arr = pancreatic_cancer_mols[0]['molecule_properties']


arr['active'] = 0
arr_labels = []
for key in arr.keys():
    arr_labels.append(key)
a = []
for i in range(23):
    a.append([])   
    


for q in range(0,23):
    a[q].append(arr[arr_labels[q]])
    


index2 = []
for p in range(1,30):
    count = 1
    list1 = pancreatic_cancer_mols[p]['molecule_properties']
    if list1 != None:
      list1['active'] = 0
      if pancreatic_cancer_mols[p]['molecule_properties'] != None and pancreatic_cancer_mols[p]['molecule_properties']['alogp'] != None and pancreatic_cancer_mols[p]['molecule_properties']['full_mwt'] != None:
        if float(pancreatic_cancer_mols[p]['molecule_properties']['full_mwt']) <= float(300):
          for j in range(0,23):
              a[j].append(list1[arr_labels[j]])
          count += 1

l2 = len(a[0])
def makeDict(list1, list2):
    new_Dict = {}
    for i in range(0,23):
        new_Dict[list1[i]] = list2[i]
    return new_Dict

for i in range(l1+1, l1 + l2 + 1):
    index2.append(i)
    
dataPan = pd.DataFrame(data = makeDict(arr_labels, a), index = index2)
dataPan = dataPan[arr_labels]
dataPan.head()

acd_logd acd_logp acd_most_apka  ... ro3_pass rtb  active
27     2.08     3.73          11.2  ...        N   4       0
28     -0.8     -0.6          7.63  ...        N   1       0
29    -2.22    -2.22         11.65  ...        N   2       0
30    -1.17    -1.17         11.75  ...        Y   0       0
31    -4.64    -0.12         -0.43  ...        N   1       0

[5 rows x 23 columns]

In [0]:
import pandas as pd



    
arr = tb_mols[0]['molecule_properties']


arr['active'] = 0
arr_labels = []
for key in arr.keys():
    arr_labels.append(key)
a = []
for i in range(23):
    a.append([])   
    


for q in range(0,23):
    a[q].append(arr[arr_labels[q]])
    


index2 = []
for p in range(1,40):
    count = 1
    list1 = tb_mols[p]['molecule_properties']
    if list1 != None:
      list1['active'] = 0
      if list1 != None and list1['alogp'] != None and list1['full_mwt'] != None:
        if float(list1['full_mwt']) <= float(400):
          for j in range(0,23):
              a[j].append(list1[arr_labels[j]])
          count += 1

l2 = len(a[0])
def makeDict(list1, list2):
    new_Dict = {}
    for i in range(0,23):
        new_Dict[list1[i]] = list2[i]
    return new_Dict

for i in range(l1+1, l1 + l2 + 1):
    index2.append(i)
    
datatb = pd.DataFrame(data = makeDict(arr_labels, a), index = index2)
datatb = datatb[arr_labels]
datatb.head()

acd_logd acd_logp acd_most_apka  ... ro3_pass rtb  active
27    -0.62     0.57          None  ...        Y   1       0
28     0.47     0.59          None  ...        N   5       0
29    -0.15      2.1          6.43  ...        N   4       0
30    -0.39     1.85          5.19  ...        N   2       0
31    -0.54     0.66          5.81  ...        N   3       0

[5 rows x 23 columns]

In [0]:
import pandas as pd



    
arr = ovary_cancer_mols[0]['molecule_properties']


arr['active'] = 0
arr_labels = []
for key in arr.keys():
    arr_labels.append(key)
a = []
for i in range(23):
    a.append([])   
    


for q in range(0,23):
    a[q].append(arr[arr_labels[q]])
    


index2 = []
for p in range(1,30):
    count = 1
    list1 = ovary_cancer_mols[p]['molecule_properties']
    if list1 != None:
      list1['active'] = 0
      if ovary_cancer_mols[p]['molecule_properties'] != None and ovary_cancer_mols[p]['molecule_properties']['alogp'] != None and ovary_cancer_mols[p]['molecule_properties']['full_mwt'] != None:
        if float(ovary_cancer_mols[p]['molecule_properties']['full_mwt']) <= float(300):
          for j in range(0,23):
              a[j].append(list1[arr_labels[j]])
          count += 1

l3 = len(a[0])
def makeDict(list1, list2):
    new_Dict = {}
    for i in range(0,23):
        new_Dict[list1[i]] = list2[i]
    return new_Dict

for i in range(l1 + l2 +1, l1 + l2 + +l3 + 1):
    index2.append(i)
    
dataOv = pd.DataFrame(data = makeDict(arr_labels, a), index = index2)
dataOv = dataOv[arr_labels]
dataOv.head()

acd_logd acd_logp acd_most_apka  ... ro3_pass rtb  active
36    -1.68      1.4          3.48  ...        N   2       0
37     2.34     2.34          9.48  ...        N   8       0
38    -2.22    -2.22         11.65  ...        N   2       0
39     0.73     0.73          None  ...        N   5       0

[4 rows x 23 columns]

In [0]:
frames = [dataLung, dataOv, dataPan]

dataComb = pd.concat(frames)

dataComb.head()

acd_logd acd_logp acd_most_apka  ... ro3_pass rtb  active
1    -0.62     0.57          None  ...        Y   1       1
2    -1.68      1.4          3.48  ...        N   2       1
3     1.04     1.04          None  ...        N   4       1
4     -1.8     -1.8         10.56  ...        N   0       1
5     0.33     0.33          10.7  ...        N   1       1

[5 rows x 23 columns]

In [0]:
frames = [dataLung, datatb]

dataComb = pd.concat(frames)

dataComb.head()

acd_logd acd_logp acd_most_apka  ... ro3_pass rtb  active
1    -0.62     0.57          None  ...        Y   1       1
2    -1.68      1.4          3.48  ...        N   2       1
3     3.62     6.26          4.73  ...        N   5       1
4     1.04     1.04          None  ...        N   4       1
5     -1.8     -1.8         10.56  ...        N   0       1

[5 rows x 23 columns]

In [0]:
orig = len(dataComb)

dataComb.drop(labels = ['full_molformula', "acd_most_apka","acd_most_bpka","molecular_species","acd_logd","acd_logp"],axis = 1,inplace= True)

dataComb['ro3_pass'].replace(to_replace=['Y'], value = 1,inplace=True)
dataComb['ro3_pass'].replace(to_replace = ['N'], value = 0, inplace=True)

dataComb = dataComb.apply(pd.to_numeric, errors = 'ignore')

y = dataComb['active'].values

dataComb.drop(labels = ['active'],axis = 1,inplace= True)
X = dataComb.iloc[::].values

In [0]:
from statistics import median
import numpy as np
import math
for i in range(0,l2 +l1):
    for j in range(0, len(X[i])):
        lst = []
        if math.isnan(X[i][j]):
            for b in range(0,l2+l1):
                if math.isnan(X[b][j]) == False:
                    
                    lst.append(X[b][j])
            X[i][j] = median(lst)
            
for i in range(0,l2+l1):
    for j in range(0, len(X[i])):
        X[i][j] = np.float32(X[i][j])
def median(lst):
    sortedLst = sorted(lst)
    lstLen = len(lst)
    index = (lstLen - 1) // 2

    if (lstLen % 2):
        return sortedLst[index]
    else:
        return (sortedLst[index] + sortedLst[index + 1])/2.0

In [0]:
#model = random forest classifier
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators = 200)
rf.fit(X_train,y_train)
pred1 = rf.predict(X_test)
#accuracy
from sklearn.metrics import accuracy_score
score = accuracy_score(y_test,pred1)

In [0]:
X_test1.head()

alogp  aromatic_rings    full_mwt  hba  ...    psa  qed_weighted  ro3_pass  rtb
1  1.4956               0  143.965889    2  ...  29.46      0.281156         1    3
2  2.2278               0  205.949798    1  ...  20.23      0.539615         1    5
3  1.6738               0  171.013174    2  ...  32.26      0.486709         1    5
4  1.6607               0  152.051988    1  ...  20.23      0.468844         1    5
5  1.0485               0  123.000287    2  ...  29.10      0.448464         1    3

[5 rows x 16 columns]

In [0]:
pred2 = rf.predict(X_test1)

In [0]:
pred2

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 0])

In [0]:
score

0.7333333333333333

In [0]:
#evolutionary algo approach

!pip install deap update_checker tqdm
!pip install tpot

     |████████████████████████████████| 153kB 4.9MB/s 
     |████████████████████████████████| 81kB 5.3MB/s 
  Created wheel for stopit: filename=stopit-1.1.2-cp36-none-any.whl size=11955 sha256=ae0495bc42cee0640535fc535b92c47ca0b553ca3df201bf92c7e04a84b070ad
  Stored in directory: /root/.cache/pip/wheels/3c/85/2b/2580190404636bfc63e8de3dff629c03bb795021e1983a6cc7
Successfully built stopit


In [0]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
%matplotlib inline 
from sklearn import preprocessing 
from sklearn.metrics import mean_squared_error 

In [0]:
#a final properties array

props = ["alogp" ,"aromatic_rings", "full_molformula","full_mwt", "hba", "hba_lipinski","hbd", "hbd_lipinski",'heavy_atoms', "mw_freebase","mw_monoistopic","num_lipinski_ro5_violations", "num_ro5_violations","psa","qed_weighted", "ro3_pass","rtb"]

In [0]:
# finally building model using tpot library
from tpot import TPOTRegressor
X_train, X_test, y_train, y_test = train_test_split(X, y,
 train_size=0.75, test_size=0.25)

tpot = TPOTRegressor(generations=12, population_size=50, verbosity=2)
tpot.fit(X_train, y_train)
print(tpot.score(X_test, y_test))

Generation 1 - Current best internal CV score: -0.23489400295640578
Generation 2 - Current best internal CV score: -0.23245518462306203
Generation 3 - Current best internal CV score: -0.23245518462306203
Generation 4 - Current best internal CV score: -0.23245518462306203
Generation 5 - Current best internal CV score: -0.23245518462306203

Best pipeline: LassoLarsCV(Binarizer(input_matrix, threshold=0.7000000000000001), normalize=False)
-0.21793871924841313


In [0]:
tpot_pred = tpot.predict(X_test)
for i in range(0,len(tpot_pred)):
  tpot_pred[i] = int(round(tpot_pred[i]))
  
tpot_pred

array([1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 0., 1.,
       1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1.])

In [0]:
y_test

array([1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 0])

In [0]:
#my pred

tpot_pred1 = tpot.predict(X_test1)


In [0]:
tpot_pred1

array([0.64466242, 0.64466242, 0.64466242, 0.64466242, 0.64466242,
       0.64466242, 0.64466242, 0.64466242, 0.64466242, 0.64466242])

In [0]:
!pip install tpot

     |████████████████████████████████| 81kB 5.1MB/s 
     |████████████████████████████████| 153kB 15.3MB/s 
  Created wheel for stopit: filename=stopit-1.1.2-cp36-none-any.whl size=11955 sha256=e0e636ad3ccdd960bb90a73b5472e7d49130f3391c2f42244d3f1f845494e4ec
  Stored in directory: /root/.cache/pip/wheels/3c/85/2b/2580190404636bfc63e8de3dff629c03bb795021e1983a6cc7
Successfully built stopit


In [0]:
# finally building model using tpot library
from tpot import TPOTClassifier
X_train, X_test, y_train, y_test = train_test_split(X, y,
 train_size=0.75, test_size=0.25)

tpot = TPOTClassifier(generations=10, population_size=100, verbosity=2)
tpot.fit(X_train, y_train)
print(tpot.score(X_test, y_test))

Generation 1 - Current best internal CV score: 0.7722222222222221
Generation 2 - Current best internal CV score: 0.7722222222222221
Generation 3 - Current best internal CV score: 0.7722222222222221
Generation 4 - Current best internal CV score: 0.8166666666666667
Generation 5 - Current best internal CV score: 0.8166666666666667
Generation 6 - Current best internal CV score: 0.8166666666666667
Generation 7 - Current best internal CV score: 0.8166666666666667
Generation 8 - Current best internal CV score: 0.8166666666666667
Generation 9 - Current best internal CV score: 0.8166666666666667
Generation 10 - Current best internal CV score: 0.8166666666666667

Best pipeline: GradientBoostingClassifier(XGBClassifier(input_matrix, learning_rate=0.1, max_depth=1, min_child_weight=11, n_estimators=100, nthread=1, subsample=0.6500000000000001), learning_rate=0.1, max_depth=5, max_features=0.5, min_samples_leaf=2, min_samples_split=9, n_estimators=100, subsample=0.8)
0.6


GradientBoostingClassifier = 0.6

In [0]:
tpot_testpred = tpot.predict(X_test)
tpot_testpred

array([1, 1, 1, 1, 1, 1, 0, 1, 1, 0])

In [0]:
y_test

array([1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 1])

In [0]:
from sklearn.metrics import accuracy_score

In [0]:
score = accuracy_score(y_test,tpot_testpred)
score

0.5172413793103449

In [0]:
tpot_pred2 = tpot.predict(X_test1)
tpot_pred2

array([1, 1, 1, 1, 1, 0, 1, 1, 0, 0])

In [0]:
#xgboost model

!pip3 install xgboost

In [0]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [0]:
X_train

array([[ 2.90000010e+00,  1.00000000e+00,  2.37729996e+02,
         2.00000000e+00,  2.00000000e+00,  1.00000000e+00,
         1.00000000e+00,  1.60000000e+01,  2.37729996e+02,
         2.37091995e+02,  0.00000000e+00,  0.00000000e+00,
         2.91000004e+01,  8.60000014e-01,  1.00000000e+00,
         2.00000000e+00],
       [ 3.34999990e+00,  2.00000000e+00,  2.55360001e+02,
         2.00000000e+00,  2.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  1.90000000e+01,  2.55360001e+02,
         2.55162292e+02,  0.00000000e+00,  0.00000000e+00,
         1.24700003e+01,  7.79999971e-01,  0.00000000e+00,
         6.00000000e+00],
       [ 1.86000001e+00,  2.00000000e+00,  2.32279999e+02,
         2.00000000e+00,  4.00000000e+00,  2.00000000e+00,
         2.00000000e+00,  1.70000000e+01,  2.32279999e+02,
         2.32121201e+02,  0.00000000e+00,  0.00000000e+00,
         5.41199989e+01,  8.39999974e-01,  0.00000000e+00,
         4.00000000e+00],
       [ 1.14999998e+00,  1.00000000e

In [0]:
from xgboost import XGBClassifier
classifier = XGBClassifier(learning_rate =0.01, n_estimators=7500, max_depth=4,min_child_weight=6, gamma=0, 
                           subsample=0.8, colsample_bytree=0.8,
                           reg_alpha=0.005, objective= 'binary:logistic', nthread=4, scale_pos_weight=1,seed=27)
classifier.fit(X_train,y_train)                          
#prediction
y_pred = classifier.predict(X_test)                           
from sklearn.metrics import accuracy_score                           
score = accuracy_score(y_test,y_pred)                           
score                           
                           


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=0.8, gamma=0,
              learning_rate=0.01, max_delta_step=0, max_depth=4,
              min_child_weight=6, missing=None, n_estimators=7500, n_jobs=1,
              nthread=4, objective='binary:logistic', random_state=0,
              reg_alpha=0.005, reg_lambda=1, scale_pos_weight=1, seed=27,
              silent=None, subsample=0.8, verbosity=1)

In [0]:
y_pred1 = classifier.predict(X_test1)

ValueError: ignored

In [0]:
y_pred1